base:
  build: .
  ports:
    - "4400:4400"
  environment:
    PORT: 4400
    NODE_PATH: app/src
  container_name: gfw-forms-api
mongo:
  image: mongo
  container_name: gfw-forms-mongo
  ports:
    - "27017"
  volumes:
    - $HOME/docker/data/gfw-forms-api:/data/db
  restart: always
