develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35736:35729"
  container_name: gfw-forms-develop
  environment:
    NODE_ENV: dev
    QUEUE_URL: redis://mymachine:6379
    QUEUE_PROVIDER: redis
    QUEUE_NAME: mail
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:4400
    WRI_MAIL_RECIPIENTS: <mails>
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFhMTBkN2M2ZTBhMzcxMjY2MTFmZDdhNyIsInJvbGUiOiJBRE1JTiIsInByb3ZpZGVyIjoibG9jYWwiLCJlbWFpbCI6ImFkbWluQGNvbnRyb2wtdG93ZXIub3JnIiwiZXh0cmFVc2VyRGF0YSI6eyJhcHBzIjpbInJ3IiwiZ2Z3IiwiZ2Z3LWNsaW1hdGUiLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJkYXRhNHNkZ3MiXX19.FglwGCDjeh5c3bdmV0GA6QiMd-I1AdbdHCLQQGUPRxw
    GOOGLE_PRIVATE_KEY: <key>
    GOOGLE_PROJECT_EMAIL: <mail>
    TARGET_SHEET_ID: <sheet>
    S3_ACCESS_KEY_ID: <key>
    S3_SECRET_ACCESS_KEY: <key>
    S3_BUCKET: <key>
  command: develop
  volumes:
    - ./app:/opt/gfw-forms-api/app
  links:
    - mongo
mongo:
  extends:
    file: base.yml
    service: mongo
